"""fix

Revision ID: 21b871cf927e
Revises: 660082aa1868
Create Date: 2021-12-05 22:19:41.312774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b871cf927e'
down_revision = '660082aa1868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
