"""Add created date to user table

Revision ID: 2ae57ac29e4d
Revises: 5112d90abad6
Create Date: 2021-11-21 23:33:35.344540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae57ac29e4d'
down_revision = '5112d90abad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'creation_date')
    # ### end Alembic commands ###
