"""fix

Revision ID: 660082aa1868
Revises: 9fd0259e9df0
Create Date: 2021-12-05 15:51:37.506889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660082aa1868'
down_revision = '9fd0259e9df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
