"""change nullable fields in order

Revision ID: 76b11a7188dc
Revises: 5c144d66d54a
Create Date: 2022-01-12 00:43:36.006225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76b11a7188dc'
down_revision = '5c144d66d54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'created_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'updated_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('order', 'orientation',
               existing_type=postgresql.ENUM('portrait', 'landscape', name='pageorientation'),
               nullable=True)
    op.alter_column('order', 'proportions',
               existing_type=postgresql.ENUM('one_to_one', 'two_to_three', 'three_to_four', 'sixteen_to_nine', name='pageproportions'),
               nullable=True)
    op.alter_column('order', 'file_format',
               existing_type=postgresql.ENUM('jpg', 'png', 'raw', 'tiff', name='fileformat'),
               nullable=True)
    op.alter_column('order', 'post_processing',
               existing_type=postgresql.ENUM('removing_defects', 'color_correction', name='postprocessing'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'post_processing',
               existing_type=postgresql.ENUM('removing_defects', 'color_correction', name='postprocessing'),
               nullable=False)
    op.alter_column('order', 'file_format',
               existing_type=postgresql.ENUM('jpg', 'png', 'raw', 'tiff', name='fileformat'),
               nullable=False)
    op.alter_column('order', 'proportions',
               existing_type=postgresql.ENUM('one_to_one', 'two_to_three', 'three_to_four', 'sixteen_to_nine', name='pageproportions'),
               nullable=False)
    op.alter_column('order', 'orientation',
               existing_type=postgresql.ENUM('portrait', 'landscape', name='pageorientation'),
               nullable=False)
    op.alter_column('order', 'updated_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('order', 'created_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
